<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class LetterBody extends Model
{
    protected $fillable = [
        'slug',
        'title',
        'description',
    ];

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (LetterBody $letterBody) {
            $letterBody->slug = Str::uuid()->toString();
        });
    }

    public function getRouteKeyName(): string
    {
        return 'slug';
    }
}
